# Generated by Django 3.2.5 on 2023-02-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saudadesemfim', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phots',
            new_name='Photos',
        ),
    ]
