# Generated by Django 3.2.5 on 2023-02-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saudadesemfim', '0002_rename_phots_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='photos_list',
        ),
        migrations.AddField(
            model_name='photos',
            name='photos_item',
            field=models.ImageField(default='fachada.jpg', max_length=2000, upload_to=''),
        ),
        migrations.AddField(
            model_name='photos',
            name='photos_name',
            field=models.CharField(default='fachada.jpg', max_length=200),
        ),
    ]
