# Generated by Django 4.1.6 on 2023-03-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saudadesemfim', '0003_auto_20230226_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photos_item',
            field=models.ImageField(default='fachada.jpg', max_length=2000, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photos_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
