# Generated by Django 4.1.6 on 2023-03-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saudadesemfim', '0004_alter_photos_photos_item_alter_photos_photos_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepagePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos_name', models.CharField(blank=True, default='', max_length=200)),
                ('photos_item', models.ImageField(default='', max_length=2000, upload_to='media')),
            ],
        ),
    ]
