# Generated by Django 4.1.6 on 2023-03-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saudadesemfim', '0006_homepagephotosmobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuemSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_quemsomos', models.TextField()),
            ],
        ),
    ]
