# Generated by Django 4.1.6 on 2023-03-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saudadesemfim', '0007_quemsomos'),
    ]

    operations = [
        migrations.AddField(
            model_name='quemsomos',
            name='photos_item',
            field=models.ImageField(default='', max_length=2000, upload_to='media'),
        ),
    ]
