# Generated by Django 4.1.6 on 2023-03-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saudadesemfim', '0008_quemsomos_photos_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlforrecaImagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos_name', models.CharField(blank=True, default='', max_length=200)),
                ('photos_item', models.ImageField(default='', max_length=2000, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='AlforrecaTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_alforreca', models.TextField()),
            ],
        ),
    ]
