# Generated by Django 4.1.6 on 2023-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saudadesemfim', '0009_alforrecaimagens_alforrecatexto'),
    ]

    operations = [
        migrations.AddField(
            model_name='alforrecatexto',
            name='photos_item',
            field=models.ImageField(default='', max_length=2000, upload_to='media'),
        ),
    ]
