# Generated by Django 4.1.6 on 2023-04-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saudadesemfim', '0010_alforrecatexto_photos_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComoChegar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('images', models.ImageField(default='', max_length=2000, upload_to='media')),
            ],
        ),
    ]
