# Generated by Django 4.1.6 on 2023-04-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saudadesemfim', '0011_comochegar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comochegar',
            name='images',
        ),
    ]
